# Generated by Django 2.2.3 on 2019-07-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body', models.TextField(blank=True, db_index=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users_list',
        ),
    ]
