# Generated by Django 2.2.3 on 2019-07-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lib', '0002_auto_20190703_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_name',
            name='body',
        ),
        migrations.AddField(
            model_name='user_name',
            name='tags',
            field=models.ManyToManyField(to='test_lib.Tag'),
        ),
    ]
