# Generated by Django 2.2.3 on 2019-07-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lib', '0003_auto_20190703_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_name',
            name='tags',
            field=models.ManyToManyField(blank=True, to='test_lib.Tag'),
        ),
    ]
