# Generated by Django 2.2.3 on 2019-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_lib', '0004_auto_20190703_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_name',
            name='body',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
